# Workflow name
name: 🚀 Storybook 배포

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: ✅ 코드 체크아웃
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 🚀 Storybook 배포
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
